### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId" : 1,
  "accountNumber" : "1000000002",
  "amount" : 20000
}


### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId" : "148a5f9008084d6fa8fa5ca0a114b451",
  "accountNumber" : "1000000002",
  "amount" : 20000
}

### get transaction
GET http://localhost:8080/transaction/a7c8c093e4eb4703872310ed996f538f
